_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    OUTPUT_LAYER: "CosSimNegHead"
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
    NUM_CLASSES: 80
    FREEZE_FEAT: False
    CLS_DROPOUT: True
    COS_SCALE: 3
    NEG_MODE: 3
    NEG_WEIGHT: 0.3
    NEG_EMB_TYPE: 'att'
    NEG_REP_TYPE: 'fc_weight'
    NEG_CHANNELS: 2048
    NEG_INPUT_DETACH: True
    ADD_REG_FC: True
    REG_FC_CHANNELS: 2048
  ROI_BOX_HEAD:
    REG_LOSS_WEIGHT: 2.0
    USE_TRIPLET: True
    TRIPLET_MARGIN: 0.1
    USE_NEG_TRIPLET: True
    TRIPLET_NEG_MARGIN: 0.1
    NEG_THRESH: 0.3
    NEG_IOU_THRESH: (0.3, 0.4)
#INPUT:
#  MIN_SIZE_TRAIN: (440, 472, 504, 536, 568, 600)
#  MIN_SIZE_TEST: 600
#  MAX_SIZE_TRAIN: 1000
#  MAX_SIZE_TEST: 1000
DATASETS:
  TRAIN: ('coco14_trainval_all_2shot_seedx',)
  TEST: ('coco14_test_all',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (4000,)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 400000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: False
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
  EVAL_PERIOD: 4000
OUTPUT_DIR: "/Path/to/Output/Dir"