from detectron2.config.defaults import _C
from detectron2.config import CfgNode as CN

_CC = _C

# ----------- Backbone ----------- #
_CC.MODEL.BACKBONE.FREEZE = False
_CC.MODEL.BACKBONE.FREEZE_AT = 3

# ------------- RPN -------------- #
_CC.MODEL.RPN.FREEZE = False
_CC.MODEL.RPN.ENABLE_DECOUPLE = False
_CC.MODEL.RPN.BACKWARD_SCALE = 1.0

# ------------- ROI -------------- #
_CC.MODEL.ROI_HEADS.NAME = "Res5ROIHeads"
_CC.MODEL.ROI_HEADS.FREEZE_FEAT = False
_CC.MODEL.ROI_HEADS.ENABLE_DECOUPLE = False
_CC.MODEL.ROI_HEADS.BACKWARD_SCALE = 1.0
_CC.MODEL.ROI_HEADS.OUTPUT_LAYER = "FastRCNNOutputLayers"
_CC.MODEL.ROI_HEADS.CLS_DROPOUT = False
_CC.MODEL.ROI_HEADS.DROPOUT_RATIO = 0.8
_CC.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION = 7  # for faster
_CC.MODEL.ROI_BOX_HEAD.CLS_AGNOSTIC_BBOX_REG = False

_CC.MODEL.ROI_HEADS.ADD_GLOBAL = False
_CC.MODEL.ROI_HEADS.REP_CHANNELS = None
_CC.MODEL.ROI_HEADS.COS_SCALE = 3
_CC.MODEL.ROI_HEADS.COS_POWER = 2
_CC.MODEL.ROI_HEADS.NEG_MODE = 3
_CC.MODEL.ROI_HEADS.NEG_WEIGHT = 0.5
_CC.MODEL.ROI_HEADS.BG_REFINE = False
_CC.MODEL.ROI_HEADS.FG_CHANNEL_ATTENTION = False
_CC.MODEL.ROI_HEADS.NEG_COS_ITER = 0
_CC.MODEL.ROI_HEADS.REG2CLS_ATTENTION = False
_CC.MODEL.ROI_HEADS.NEG_CHANNELS = 2048
_CC.MODEL.ROI_HEADS.REP_SIM_LOSS = False
_CC.MODEL.ROI_HEADS.BASE_NOVEL_SIM_LOSS = False
_CC.MODEL.ROI_HEADS.NUM_BASE_CLASSES = 15
_CC.MODEL.ROI_HEADS.NUM_NOVEL_CLASSES = 5
_CC.MODEL.ROI_HEADS.BASE_NOVEL_CLS_LOSS = False
_CC.MODEL.ROI_HEADS.SIM_MAT_LOSS = False
_CC.MODEL.ROI_HEADS.BG_FG_HN_CLS_LOSS = False
_CC.MODEL.ROI_HEADS.BFH_START_ITER = 1000
_CC.MODEL.ROI_HEADS.HN_HEAD = False
_CC.MODEL.ROI_HEADS.HN_HEAD_ABS = False
_CC.MODEL.ROI_HEADS.HN_TYPE = 'hn_type1'
_CC.MODEL.ROI_HEADS.ADD_SOFTMAX_CLS = False
_CC.MODEL.ROI_HEADS.ADD_UK_HEAD = False
_CC.MODEL.ROI_HEADS.NEG_REP_TYPE = 'fc_weight'
_CC.MODEL.ROI_HEADS.NEG_EMB_TYPE = 'none'
_CC.MODEL.ROI_HEADS.NEG_INPUT_DETACH = True
_CC.MODEL.ROI_HEADS.BATCH_NORM = False
_CC.MODEL.ROI_HEADS.HN_SELECTION = 1
_CC.MODEL.ROI_HEADS.ATT_WEIGHT = 1.
_CC.MODEL.ROI_HEADS.NEG_TRIPLET_LOSS_TYPE = 'neg_triplet_loss'
_CC.MODEL.ROI_HEADS.HN_TRIPLET_LOSS = False
_CC.MODEL.ROI_HEADS.HN_TRIPLET_MARGIN = 0.2
_CC.MODEL.ROI_HEADS.ADD_REG_FC = False
_CC.MODEL.ROI_HEADS.REG_FC_CHANNELS = 2048
_CC.MODEL.ROI_HEADS.ADD_CLS_FC = False
_CC.MODEL.ROI_HEADS.CLS_FC_CHANNELS = 2048
_CC.MODEL.ROI_HEADS.ADD_DISTILL = False
_CC.MODEL.ROI_HEADS.FREEZE_BASE_REP = False

_CC.MODEL.ROI_BOX_HEAD.USE_TRIPLET = False
_CC.MODEL.ROI_BOX_HEAD.TRIPLET_MARGIN = 0.15
_CC.MODEL.ROI_BOX_HEAD.USE_PN_TRIPLET = False
_CC.MODEL.ROI_BOX_HEAD.USE_NEG_TRIPLET = False
_CC.MODEL.ROI_BOX_HEAD.TRIPLET_NEG_MARGIN = 0.1
_CC.MODEL.ROI_BOX_HEAD.NEG_THRESH = 0.1
_CC.MODEL.ROI_BOX_HEAD.NEG_IOU_THRESH = (0.2, 0.3)
_CC.MODEL.ROI_BOX_HEAD.METRIC_TYPE = 'cos_sim'
_CC.MODEL.ROI_BOX_HEAD.CLS_LOSS_TYPE = 'focal_loss'
_CC.MODEL.ROI_BOX_HEAD.FL_GAMMA = 2.0
_CC.MODEL.ROI_BOX_HEAD.FL_ALPHA = 0.25
_CC.MODEL.ROI_BOX_HEAD.REG_LOSS_WEIGHT = 1.0


# ------------- TEST ------------- #
_CC.TEST.PCB_ENABLE = False
_CC.TEST.PCB_MODELTYPE = 'resnet'             # res-like
_CC.TEST.PCB_MODELPATH = ""
_CC.TEST.PCB_ALPHA = 0.50
_CC.TEST.PCB_UPPER = 1.0
_CC.TEST.PCB_LOWER = 0.05

# ------------ Other ------------- #
_CC.SOLVER.WEIGHT_DECAY = 5e-5
_CC.MUTE_HEADER = True

_C.SOLVER.WARMUP_FACTOR = 1.0 / 1000
_C.SOLVER.WARMUP_ITERS = 1000