VERSION: 2
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeads"
    COS_SCALE: 3
    NEG_MODE: 3
    NEG_WEIGHT: 0.5
  ROI_BOX_HEAD:
    USE_TRIPLET: True
    TRIPLET_MARGIN: 0.15
    USE_NEG_TRIPLET: True
    TRIPLET_NEG_MARGIN: 0.1
    NEG_THRESH: 0.1
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
TEST:
#  EVAL_PERIOD: 2000
  PCB_MODELTYPE: 'resnet'