_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/ImageNet/Pretrain/Weight"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
  ROI_HEADS:
    OUTPUT_LAYER: "CosSimNegHead"
    NUM_CLASSES: 15
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
    COS_SCALE: 3
    NEG_MODE: 3
    NEG_WEIGHT: 0.3
    SCORE_THRESH_TEST: 0.05
    NEG_EMB_TYPE: 'att'
    NEG_REP_TYPE: 'fc_weight'
    NEG_CHANNELS: 2048
    NEG_INPUT_DETACH: True
    ADD_REG_FC: True
    REG_FC_CHANNELS: 2048
  ROI_BOX_HEAD:
    REG_LOSS_WEIGHT: 1.0
    USE_TRIPLET: True
    TRIPLET_MARGIN: 0.15
    USE_NEG_TRIPLET: True
    TRIPLET_NEG_MARGIN: 0.1
    NEG_THRESH: 0.3
    NEG_IOU_THRESH: (0.3, 0.4)
TEST:
  EVAL_PERIOD: 3000
INPUT:
  MIN_SIZE_TRAIN: (302, 334, 376, 408, 440, 472, 504, 536, 568, 600)
  MIN_SIZE_TEST: 600
  MAX_SIZE_TRAIN: 1000
  MAX_SIZE_TEST: 1000
DATASETS:
  TRAIN: ('voc_2007_trainval_base2', 'voc_2012_trainval_base2')
  TEST: ('voc_2007_test_base2',)
SOLVER:
  STEPS: (10000, 13300)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 15000
  WARMUP_ITERS: 100
OUTPUT_DIR: "/Path/to/Output/Dir"